### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Adogs1** [zihao-il/zihao-il.github.io#1]
为什么测试版的所需存储空间最新版在500M左右，而正式版却是800MB呢？是少了什么游戏内容吗？

**Comment by zihao-il** [comment]
因为测试版把音乐包压缩了

**Comment by zihao-il** [comment]
> 为什么测试版的所需存储空间最新版在500M左右，而正式版却是800MB呢？是少了什么游戏内容吗？

因为测试版把音乐包压缩了

**Comment by Adogs1** [comment]
> > 为什么测试版的所需存储空间最新版在500M左右，而正式版却是800MB呢？是少了什么游戏内容吗？
> 
> 因为测试版把音乐包压缩了

这样不会影响游戏体验吗？如果不影响，我认为正式版应该也可以这么做

**Comment by zihao-il** [comment]
> > > 为什么测试版的所需存储空间最新版在500M左右，而正式版却是800MB呢？是少了什么游戏内容吗？
> > 
> > 
> > 因为测试版把音乐包压缩了
> 
> 这样不会影响游戏体验吗？如果不影响，我认为正式版应该也可以这么做

不影响，等正式版更新到测试版内容的时候就会压缩音乐包的

**Comment by Adogs1** [comment]
> > > > 为什么测试版的所需存储空间最新版在500M左右，而正式版却是800MB呢？是少了什么游戏内容吗？
> > > 
> > > 
> > > 因为测试版把音乐包压缩了
> > 
> > 
> > 这样不会影响游戏体验吗？如果不影响，我认为正式版应该也可以这么做
> 
> 不影响，等正式版更新到测试版内容的时候就会压缩音乐包的

谢谢你的解答
